version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql/data/
  backend:
    build:
      dockerfile: ./dockerization/Dockerfile
    env_file:
      - ./.env
    command: sh -c "
            alembic upgrade head
            && python main.py
            "
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./services/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend